# syntax=docker/dockerfile:1

# ---- build ----------------------------------------------------------------
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG TARGETARCH
WORKDIR /src

COPY global.json Directory.Build.props Directory.Packages.props .editorconfig ./
COPY src/ src/

# ReadyToRun cuts cold-start time after App Service restarts. The OpenAPI document is
# generated by CI, not inside the image build.
RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet publish src/Pegadas.Api/Pegadas.Api.csproj \
      --configuration Release \
      --arch $TARGETARCH \
      --self-contained false \
      --output /app \
      -p:PublishReadyToRun=true \
      -p:OpenApiGenerateDocuments=false

# ---- runtime --------------------------------------------------------------
# Chiseled: no shell or package manager, runs as non-root. "extra" adds ICU and tzdata,
# which school time zones need.
FROM mcr.microsoft.com/dotnet/aspnet:10.0-noble-chiseled-extra AS runtime
WORKDIR /app
COPY --from=build /app .

ENV ASPNETCORE_HTTP_PORTS=8080 \
    DOTNET_gcServer=1
EXPOSE 8080

USER $APP_UID
ENTRYPOINT ["dotnet", "Pegadas.Api.dll"]
